### ISSUE TITLE
Mutilate update

### ISSUE THREAD

**Issue by gilmors79** [DeadJim606/Mutilate#13]
I have updated to your version this morning and tested, found the following things missing for assassination spec:
1. Toxic Blade is not yet included in the rotation.
2. Voice prompt for Blindside is missin

**Comment by DeadJim606** [comment]
Can you confirm you're running V3.03?  I added Blindside voice prompt and adjusted the Toxic Blade logic with that release.

**Comment by gilmors79** [comment]
Updated to V3.03 both working and thanks for adding the Vendetta voice prompt as well

**Comment by DeadJim606** [comment]
Awesome - I'm going to close this Issue.

Also, I'm writing up changes for V3.04 which I hope to release today.  For Assassination, not much has changed in terms of rotation - it's mostly Combat and Sub, but the one-screen prompts are changing a bit (Dropped Tricks, added Evasion and Feint)
